Repository Wesleyhmendes/Byte-for-Bite, pull requests merged in 2024-03, with the labels that each got.

#54 Feat. Database data/ Fix. drinkDetails/ Stylezation drinkDetails
  app/backend/jsons/drinksRecipes.db.json
  app/backend/jsons/mealRecipes.db.json
  app/frontend/src/components/DrinkCard/index.tsx
  app/frontend/src/pages/RecipeDetails/index.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInProgress.styles.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeIngredients.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInstructions.tsx
  app/frontend/src/pages/RecipeInProgress/index.tsx
Labels: feature

#58 Draggable Menu / New drink category / new meal category / Refactoring CategoryButton
  app/backend/jsons/drinksCategory.db.json
  app/backend/jsons/mealsCategory.db.json
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/Category/Category.styles.tsx
  app/frontend/src/components/Category/index.tsx
  app/frontend/src/components/CategoryButton/Category.styles.tsx
  app/frontend/src/components/CategoryButton/CategoryButton.tsx
  app/frontend/src/hooks/useRecipesProvider.ts
  app/frontend/src/pages/Recipes/index.tsx
Labels: feature

#59 Feat. page navigation bar
  app/frontend/src/components/Category/index.tsx
  app/frontend/src/components/Category/test.css
  app/frontend/src/components/CategoryButton/CategoryButton.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/components/RecipesMiniCard/CardText.tsx
  app/frontend/src/hooks/useRecipesProvider.ts
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/Recipes/SelectPageButtons.tsx
  app/frontend/src/pages/Recipes/index.tsx
Labels: feature

#60 Feat. Header of doneRecipes/favoriteRecipes/recipesInProgress page
  app/frontend/index.html
  app/frontend/src/assets/Images/Header/done_recipes.png
  app/frontend/src/assets/Images/Header/favorite_recipes.png
  app/frontend/src/assets/Images/Header/in_progress_recipes.png
  app/frontend/src/components/DoneOrFavoriteCard/DoneOrFavoriteCard.styles.tsx
  app/frontend/src/components/DoneOrFavoriteCard/DoneOrFavoriteCard.tsx
  app/frontend/src/components/Header/Header.styles.tsx
  app/frontend/src/components/Header/index.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/components/RecipesMiniCard/CardText.tsx
  app/frontend/src/components/RecipesMiniCard/RecipesMiniCard.tsx
  app/frontend/src/components/SearchBar/SearchBar.styles.tsx
  app/frontend/src/components/ShortHeader/ShortHeader.styles.tsx
  app/frontend/src/components/ShortHeader/index.tsx
  app/frontend/src/pages/DoneRecipes/DoneRecipes.styles.tsx
  app/frontend/src/pages/DoneRecipes/index.tsx
  app/frontend/src/pages/FavoriteRecipes/index.tsx
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/Recipes/index.tsx
Labels: feature

#61 Feat. background grey/Fix. profile responsivity
  app/frontend/src/components/Category/Category.styles.tsx
  app/frontend/src/components/DoneOrFavoriteCard/DoneOrFavoriteCard.styles.tsx
  app/frontend/src/components/FilterButtons/FilterButtons.style.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/input.css
  app/frontend/src/pages/Profile/Profile.styles.tsx
  app/frontend/src/pages/RecipeDetails/RecipeDetails.styles.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInProgress.styles.tsx
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
Labels: feature, Fix

#62 Fix. box-shadow intensity / Fix. RecipeCard img size and responsivity
  app/frontend/src/components/AsideMenu/Aside.styles.tsx
  app/frontend/src/components/Category/Category.styles.tsx
  app/frontend/src/components/DoneOrFavoriteCard/DoneOrFavoriteCard.styles.tsx
  app/frontend/src/components/FilterButtons/FilterButtons.style.tsx
  app/frontend/src/components/Footer/Footer.styles.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/components/SearchBar/SearchBar.styles.tsx
  app/frontend/src/components/ShortHeader/ShortHeader.styles.tsx
  app/frontend/src/input.css
  app/frontend/src/pages/RecipeDetails/RecipeDetails.styles.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInProgress.styles.tsx
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
Labels: Fix

#65 Fix. database categories
  app/frontend/src/components/Category/index.tsx
  app/frontend/src/components/Category/test.css
Labels: Fix

#66 [Muniz] Feat.
  app/frontend/src/assets/Icons/clock-icon.png
  app/frontend/src/assets/Icons/orangeClock.png
  app/frontend/src/assets/Icons/whiteClock.png
  app/frontend/src/components/Carousel/index.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/components/RecipesMiniCard/CardText.tsx
  app/frontend/src/components/RecipesMiniCard/RecipesMiniCard.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInfo.tsx
Labels: feature

#67 Fix. footer responsivity on desktop
  app/backend/jsons/drinksCategory.db.json
  app/backend/jsons/mealsCategory.db.json
  app/backend/src/database/models/02Meals-Categories.model.ts
  app/frontend/src/components/Footer/Footer.styles.tsx
  app/frontend/src/components/Footer/index.tsx
  app/frontend/src/hooks/useUserProvider.ts
  app/frontend/src/pages/Profile/Profile.styles.tsx
  app/frontend/src/pages/RecipeDetails/RecipeDetails.styles.tsx
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/SignUp/SignUp.styles.tsx
  app/frontend/src/pages/SignUp/SignUpForm.tsx
Labels: Fix

#68 Feat. Aside desktop menu navigation / Fix. Footer width
  app/frontend/src/components/AsideDesktopMenu/AsideDesktopMenu.styles.tsx
  app/frontend/src/components/AsideDesktopMenu/AsideDesktopMenu.tsx
  app/frontend/src/components/AsideMenu/Aside.styles.tsx
  app/frontend/src/components/Footer/Footer.styles.tsx
  app/frontend/src/components/Header/Header.styles.tsx
  app/frontend/src/components/Layout/index.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/components/RecipesMiniCard/CardText.tsx
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/Recipes/index.tsx
Labels: feature, Fix

#69 [Muniz] Fix
  app/backend/src/models/MealsModel.ts
  app/frontend/src/components/MealCard/index.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInfo.tsx
  app/frontend/src/pages/RecipeInProgress/index.tsx
  app/frontend/src/utils/getCategories.ts
Labels: Fix

#70 Feat. / Fix. - Home Page / Title / Aside Desktop Menu
  app/frontend/src/assets/Icons/AsideMenuDesktop/done_icon.png
  app/frontend/src/assets/Icons/AsideMenuDesktop/favorite_icon.png
  app/frontend/src/assets/Icons/AsideMenuDesktop/glass-icon32.png
  app/frontend/src/assets/Icons/AsideMenuDesktop/plate-icon32.png
  app/frontend/src/assets/Icons/log-out.svg
  app/frontend/src/assets/Icons/logout_icon.png
  app/frontend/src/assets/Icons/yellow-check-circle.svg
  app/frontend/src/assets/Icons/yellow-circle-heart.svg
  app/frontend/src/components/AsideDesktopMenu/AsideDesktopMenu.styles.tsx
  app/frontend/src/components/AsideDesktopMenu/AsideDesktopMenu.tsx
  app/frontend/src/components/Category/index.tsx
  app/frontend/src/components/DoneOrFavoriteCard/DoneOrFavoriteCard.tsx
  app/frontend/src/components/MealCard/index.tsx
  app/frontend/src/pages/DoneRecipes/index.tsx
  app/frontend/src/pages/FavoriteRecipes/index.tsx
  app/frontend/src/pages/Login/index.tsx
  app/frontend/src/pages/Profile/index.tsx
  app/frontend/src/pages/RecipeDetails/index.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInfo.tsx
  app/frontend/src/pages/RecipeInProgress/index.tsx
  app/frontend/src/pages/Recipes/index.tsx
  app/frontend/src/pages/SignUp/index.tsx
Labels: feature, Fix

#71 [Muniz] Fix & Refactor
  app/frontend/src/pages/DoneRecipes/index.tsx
  app/frontend/src/pages/FavoriteRecipes/index.tsx
Labels: feature

#72 Tests Implementation - Meals/Users
  app/backend/.nyc_output/13ab8728-1ce4-4898-ba5f-91f935bb1c47.json
  app/backend/.nyc_output/6ecf28d5-6508-436b-a2cc-7a11b8b9765e.json
  app/backend/.nyc_output/processinfo/13ab8728-1ce4-4898-ba5f-91f935bb1c47.json
  app/backend/.nyc_output/processinfo/6ecf28d5-6508-436b-a2cc-7a11b8b9765e.json
  app/backend/.nyc_output/processinfo/index.json
  app/backend/jsons/users.db.json
  app/backend/package-lock.json
  app/backend/package.json
  app/backend/src/controllers/MealsController.ts
  app/backend/src/models/Drinks.model.ts
  app/backend/src/models/MealsModel.ts
  app/backend/src/models/UserModel.ts
  app/backend/src/routes/meals.routes.ts
  app/backend/src/services/DrinksService.ts
  app/backend/src/services/MealsService.ts
  app/backend/src/services/ProfileService.ts
  app/backend/src/tests/integration/meals.test.ts
  app/backend/src/tests/integration/user.test.ts
  app/backend/src/tests/mocks/meal.mock.ts
  app/backend/src/tests/mocks/user.mock.ts
  app/backend/src/tests/unit/controllers/user.controller.test.ts
Labels: Tests

#75 Implement Login/SignUp with Google
  app/backend/.gitignore
  app/backend/.nyc_output/078a8a59-2111-4013-a29a-363f8f8aae65.json
  app/backend/.nyc_output/454962bb-d488-4164-a11e-8df1e554ea61.json
  app/backend/.nyc_output/processinfo/078a8a59-2111-4013-a29a-363f8f8aae65.json
  app/backend/.nyc_output/processinfo/454962bb-d488-4164-a11e-8df1e554ea61.json
  app/backend/.nyc_output/processinfo/index.json
  app/backend/src/Interfaces/IUsers.ts
  app/backend/src/controllers/UserController.ts
  app/backend/src/database/migrations/00Users.ts
  app/backend/src/database/models/00UserModel.ts
  app/backend/src/models/UserModel.ts
  app/backend/src/routes/user.routes.ts
  app/backend/src/services/UserService.ts
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/CategoryButton/CategoryButton.tsx
  app/frontend/src/components/Modals/LoginModal/Modal.styles.tsx
  app/frontend/src/main.tsx
  app/frontend/src/pages/Login/Login.styles.tsx
  app/frontend/src/pages/Login/LoginForm.tsx
  app/frontend/src/pages/Login/index.tsx
  app/frontend/src/pages/SignUp/GoogleAuth.tsx
  app/frontend/src/pages/SignUp/SignUp.styles.tsx
  app/frontend/src/pages/SignUp/SignUpForm.tsx
  app/frontend/src/pages/SignUp/index.tsx
Labels: feature
