Repository Wesleyhmendes/Byte-for-Bite, pull requests merged in 2024-04, with the labels that each got.

#79 Feat. filter clear button/ Aside menu links/ search filters style
  app/frontend/src/assets/Icons/bin.png
  app/frontend/src/components/AsideMenu/Aside.Menu.tsx
  app/frontend/src/components/AsideMenu/Aside.styles.tsx
  app/frontend/src/components/Category/Category.styles.tsx
  app/frontend/src/components/Category/index.tsx
  app/frontend/src/components/CategoryButton/Category.styles.tsx
  app/frontend/src/components/CategoryButton/CategoryButton.tsx
  app/frontend/src/components/Header/Header.styles.tsx
  app/frontend/src/components/Header/index.tsx
  app/frontend/src/components/SearchBar/SearchBar.styles.tsx
  app/frontend/src/components/SearchBar/index.tsx
  app/frontend/src/components/ShortHeader/ShortHeader.styles.tsx
  app/frontend/src/components/ShortHeader/index.tsx
  app/frontend/src/context/Context.ts
  app/frontend/src/context/Provider/Provider.tsx
  app/frontend/src/hooks/useRecipesProvider.ts
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/Recipes/index.tsx
  app/frontend/src/utils/readCtegory.ts
Labels: feature, Fix

#81 Style Components - Global variables
  app/frontend/src/components/AsideDesktopMenu/AsideDesktopMenu.styles.tsx
  app/frontend/src/components/AsideMenu/Aside.styles.tsx
  app/frontend/src/components/CategoryButton/Category.styles.tsx
  app/frontend/src/components/DoneOrFavoriteCard/DoneOrFavoriteCard.styles.tsx
  app/frontend/src/components/DoneOrFavoriteMessage/index.tsx
  app/frontend/src/components/DoneOrFavoriteMessage/message.styles.tsx
  app/frontend/src/components/DrinkCard/index.tsx
  app/frontend/src/components/FavoriteButton/Favorite.styles.tsx
  app/frontend/src/components/FavoriteButton/index.tsx
  app/frontend/src/components/FilterButtons/FilterButtons.style.tsx
  app/frontend/src/components/Footer/Footer.styles.tsx
  app/frontend/src/components/Header/Header.styles.tsx
  app/frontend/src/components/Header/index.tsx
  app/frontend/src/components/MealCard/index.tsx
  app/frontend/src/components/Modals/LoginModal/Modal.styles.tsx
  app/frontend/src/components/Modals/SignUpModal/SignUpModal.styles.tsx
  app/frontend/src/components/RecipesMiniCard/Card.styles.tsx
  app/frontend/src/components/RecipesMiniCard/CardText.tsx
  app/frontend/src/components/SearchBar/SearchBar.styles.tsx
  app/frontend/src/components/ShortHeader/ShortHeader.styles.tsx
  app/frontend/src/pages/Login/Login.styles.tsx
  app/frontend/src/pages/Profile/Profile.styles.tsx
  app/frontend/src/pages/RecipeDetails/RecipeDetails.styles.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInProgress.styles.tsx
  app/frontend/src/pages/RecipeInProgress/RecipeInfo.tsx
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/SignUp/SignUp.styles.tsx
  app/frontend/src/pages/SignUp/SignUpForm.tsx
  app/frontend/src/tests/ShareFavoriteButtons.test.tsx
  app/frontend/src/theme.tsx
Labels: feature

#99 Fix. README
  README.md
Labels: Fix

#101 Fix. burger menu
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/AsideMenu/Aside.Menu.tsx
  app/frontend/src/components/AsideMenu/Aside.styles.tsx
  app/frontend/src/hooks/useFetch.ts
Labels: Fix

#102 Feat. Clear filter button
  README.md
  app/frontend/src/components/ClearFilter/ClearFilter.tsx
  app/frontend/src/hooks/useFetch.ts
  app/frontend/src/pages/Recipes/Recipes.styles.tsx
  app/frontend/src/pages/Recipes/index.tsx
  readme-assets/1697576847994.png
  readme-assets/Macbook-Air-localhost (1).png
  readme-assets/Macbook-Air-localhost (2).png
  readme-assets/Macbook-Air-localhost.png
  readme-assets/drink_diagram.png
  readme-assets/iPhone-13-PRO-localhost (1).png
  readme-assets/iPhone-13-PRO-localhost (2).png
  readme-assets/iPhone-13-PRO-localhost (3).png
  readme-assets/iPhone-13-PRO-localhost (4).png
  readme-assets/iPhone-13-PRO-localhost.png
  readme-assets/meal_driagram.png
  readmeAssets/1697576847994.png
  readmeAssets/Macbook-Air-localhost.png
  readmeAssets/Macbook-Air-localhost_(1).png
  readmeAssets/drink_diagram.png
  readmeAssets/foto-perfil-amarela.png
  readmeAssets/iPhone-13-PRO-localhost.png
  readmeAssets/iPhone-13-PRO-localhost_(1).png
  readmeAssets/meal_driagram.png
Labels: feature

#103 [Muniz] Fix no Loading do RecipeDetails
  app/frontend/src/pages/RecipeDetails/index.tsx
Labels: Fix

#104 Fix. not found page
  app/frontend/src/assets/Images/not-found.gif
  app/frontend/src/components/Footer/Footer.styles.tsx
  app/frontend/src/components/Footer/index.tsx
  app/frontend/src/components/MealCard/index.tsx
  app/frontend/src/pages/NotFound/NotFound.style.ts
  app/frontend/src/pages/NotFound/NotFound.tsx
  app/frontend/src/pages/Profile/index.tsx
  app/frontend/src/pages/RecipeDetails/RecipeDetails.styles.tsx
  app/frontend/src/pages/RecipeDetails/index.tsx
Labels: Fix

#105 Fix. loading
  app/frontend/src/hooks/useFetch.ts
  app/frontend/src/pages/RecipeDetails/RecipeDetails.styles.tsx
  app/frontend/src/pages/RecipeDetails/index.tsx
Labels: Fix
